name: reality_gap
description: A brutally honest time tracking app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local storage
  shared_preferences: ^2.2.2

  # Android usage stats
  usage_stats: ^1.3.0

  # Date formatting
  intl: ^0.19.0

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

# App Icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"
  background_color: "#000000"

# Splash Screen config
flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/
